### ISSUE TITLE
How to arm/disarm a UAV ?

### ISSUE THREAD

**Issue by salocinx** [amin347/TestMavlink.net#1]
Hi Amin

Thanks for your example. This helped to establish a connection over RS232 to my UAV and send periodic heartbeat messages.

However, have you already managed to send a GuidedArm/GuidedDisarm message to the UAV? Any example code to get into this? MavLink has a pretty steep learning curve :-/

Regards,
salocinx

**Comment by amin347** [comment]
hi salocinx, i dont know
